
version: '3'

services:
  DataBOS:
    image: mysql:5.7
    volumes:
      - DB_ST:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: liyambotham
      MYSQL_USER: ayushman
      MYSQL_PASSWORD: Abcd@1234
      MYSQL_DATABASE: mydbase21
    restart: always

  WordPOS:
    image: wordpress:5.1.1-php7.3-apache
    volumes: 
      - WP_ST:/var/www/html
    ports:
      - 8040:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: DataBOS
      WORDPRESS_DB_USER: ayushman
      WORDPRESS_DB_PASSWORD: Abcd@1234
      WORDPRESS_DB_NAME: mydbase21
    depends_on:
      - DataBOS

  NXTCLOUD:
    image: nextcloud:latest
    volumes:
      - NC_ST:/var/www/html
    environment:
      MYSQL_DATABASE: mydbase21
      MYSQL_USER: ayushman
      MYSQL_PASSWORD: Abcd@1234
      MYSQL_HOST: DataBOS
      NEXTCLOUD_ADMIN_USER: liam@disbox.net
      NEXTCLOUD_ADMIN_PASSWORD: liam@123#
    restart: always
    depends_on:
      - DataBOS
    ports:
      - 8080:80
      - 8060:443
volumes:
  DB_ST:
  NC_ST:
  WP_ST:
